import type { RedAlertSnapshotResponse } from './redAlertTypes';

/** Deterministic sample data for UI/dev when people-api has no Red Alert route yet. */
export const RED_ALERT_DEV_MOCK_SNAPSHOT: RedAlertSnapshotResponse = {
  generatedAt: new Date().toISOString(),
  rows: [
    {
      machineName: 'Terminal A — Unit 12',
      machineId: '120441',
      operator: 'Noura K.',
      cleaningOperator: 'Half-cleaning crew (Sun block)',
      reasons: ['Stale sale interval ≥30m (cleaning excluded)', 'KNet / Machine OFF ≥30m operational'],
      alertPriorityTier: 1,
      happensWeek: 14,
      happenedLastWeek: 9,
      happenedPctVsPriorWeek: 22,
      happenedLastWeekAlignedSlice: 7.7,
      happensToday: 4,
      happenedSameDayLastWeek: 3,
      happenedPctVsSameDayLastWeek: 12,
      happenedYesterdaySameElapsed: 2,
      happenedPctVsYesterdaySameElapsed: 33,
      strikeOperatorEmail: 'field.ops@example.com',
      goCheckUrl: null,
      pfaExcludeCleaning: false,
      pfaExcludeCleaningAdmin: false,
      onCleaningSchedule: true,
      duringScheduledCleaningNow: false,
      frequency: {
        totalCriteriaHitsThisWeek: 14,
        totalCriteriaHitsLastWeek: 10,
        totalCriteriaHitsLastWeekAlignedToWtD: 7.7,
        totalCriteriaHitsToday: 4,
        totalCriteriaHitsSameDayLastWeek: 3,
        staleSaleEpisodesThisWeek: 5,
        staleSaleEpisodesLastWeek: 4,
        staleSaleEpisodesToday: 2,
        staleSaleEpisodesSameDayLastWeek: 1,
        offEpisodesThisWeek: 6,
        offEpisodesLastWeek: 4,
        offEpisodesToday: 1,
        offEpisodesSameDayLastWeek: 1,
        dispenseFailsThisWeek: 3,
        dispenseFailsLastWeek: 2,
        dispenseFailsToday: 1,
        dispenseFailsSameDayLastWeek: 1,
        staleSaleEpisodesYesterdaySameElapsed: 1,
        offEpisodesYesterdaySameElapsed: 0,
        dispenseFailsYesterdaySameElapsed: 1,
        totalCriteriaHitsYesterdaySameElapsed: 2,
      },
    },
    {
      machineName: 'Gate B — Kiosk 3',
      machineId: '120882',
      operator: 'Marco R.',
      reasons: ['Vend failed events above threshold (week)'],
      alertPriorityTier: 2,
      happensWeek: 11,
      happenedLastWeek: 11,
      happenedPctVsPriorWeek: -4,
      strikeOperatorEmail: '',
      pfaExcludeCleaning: true,
      pfaExcludeCleaningAdmin: true,
      onCleaningSchedule: true,
      duringScheduledCleaningNow: true,
      frequency: {
        totalCriteriaHitsThisWeek: 11,
        totalCriteriaHitsLastWeek: 12,
        staleSaleEpisodesThisWeek: 2,
        staleSaleEpisodesLastWeek: 3,
        offEpisodesThisWeek: 7,
        offEpisodesLastWeek: 6,
        dispenseFailsThisWeek: 2,
        dispenseFailsLastWeek: 3,
      },
    },
    {
      machineName: 'Concourse D — Unit 05',
      machineId: '119905',
      operator: 'Sara M.',
      cleaningOperator: 'Deep clean Wed',
      reasons: ['Hours without cleaning threshold', 'QC visit overdue'],
      alertPriorityTier: 1,
      happensWeek: 3,
      happenedLastWeek: 2,
      happenedPctVsPriorWeek: 0,
      strikeOperatorEmail: 'qc.lead@example.com',
      pfaExcludeCleaning: null,
      pfaExcludeCleaningAdmin: null,
      onCleaningSchedule: false,
      duringScheduledCleaningNow: false,
      frequency: {
        totalCriteriaHitsThisWeek: 3,
        totalCriteriaHitsLastWeek: 2,
        staleSaleEpisodesThisWeek: 1,
        staleSaleEpisodesLastWeek: 1,
        offEpisodesThisWeek: 1,
        offEpisodesLastWeek: 1,
        dispenseFailsThisWeek: 1,
        dispenseFailsLastWeek: 0,
      },
    },
  ],
};
